services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos_db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  client:
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5433/todos_db
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5433/todos_db
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db-data: